#!/usr/bin/env python
# -*- coding: utf-8 -*-

__author__ = "David Amian <damian@xmltravelgate.com>"
__copyright__ = "Copyright (C) 2018, TravelgateX"
__license__ = "GPL-2"

VERBOSE = False

# Environment DEV:
GRAPH_URL = "https://dev-api.travelgatex.com/"
GRAPH_TOKEN = "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ik5EQTFOa00zUVVSRk1EQXdOekF4TVRKRk5UQkdSRGMwUWpreVEwVTJOVVV6UkRrNU5rUkNSZyJ9.eyJodHRwczovL3RyYXZlbGdhdGV4LmNvbS9pYW0iOlt7ImEiOm51bGwsImMiOiJ4dGciLCJnIjpbeyJhIjp7ImFsbCI6eyJlbnRpdHkiOnsiYWNjIjpbImNydWQxYWYiXSwiY2xpIjpbImNydWQxYWYiXSwic3VwIjpbImNydWQxYWYiXSwicHJmIjpbImNydWQxYWYiXX0sImhvdGxzdCI6eyJob3QiOlsiMXgiXX0sImh1YmdyYSI6eyJib2siOlsiMXhmIl0sImJvbyI6WyIxeGYiXSwiYnJkIjpbIjF4ZiJdLCJjYXQiOlsiMXhmIl0sImNmZyI6WyIxeGYiXSwiY25sIjpbIjF4ZiJdLCJxdGUiOlsiMXhmIl0sInJvbSI6WyIxeGYiXSwic3JjIjpbIjF4ZiJdfSwiaWFtIjp7ImFwaSI6WyJjcnVkMWFmIl0sImdycCI6WyJjcnVkMWFmIl0sIm1iciI6WyJjcnVkMWFmIl0sInByZCI6WyJjcnVkMWFmIl0sInJvbCI6WyJjcnVkMWFmIl0sInJzYyI6WyJjcnVkMWFmIl19fX0sImMiOiJvbmx5X2luX2F1dGgwIiwiZyI6bnVsbCwicCI6bnVsbCwidCI6InRlYW0ifV0sInAiOnsiaWFtIjp7ImdycCI6WyJjcnVkMSJdfX0sInQiOiJyb290In1dLCJodHRwczovL3RyYXZlbGdhdGV4LmNvbS9tZW1iZXJfaWQiOiJkYW1pYW5AeG1sdHJhdmVsZ2F0ZS5jb20iLCJpc3MiOiJodHRwczovL3h0Zy1kZXYuZXUuYXV0aDAuY29tLyIsInN1YiI6IkNzM1prTmpwTUN3MmZWVDlnNnBuMGxzU0p3ZDYxUDlYQGNsaWVudHMiLCJhdWQiOiJodHRwczovL2FwaS50cmF2ZWxnYXRleC5jb20iLCJpYXQiOjE1Mzc5NTY5MjksImV4cCI6MTU0NTczMjkyOSwiYXpwIjoiQ3MzWmtOanBNQ3cyZlZUOWc2cG4wbHNTSndkNjFQOVgiLCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMifQ.EDXaiDz1Q3vBVBwbMR3dQ3LzhenrUkjvU2QoodxeAQCl8JBMod-5uuVx0aPNCWzoZLErLo4ErrNnQ1qpaTaAOE91XRCkkfrbWX1SjlRoM1W_ndE8EqvQkjxhQ5pmEzDZlYuscLGEeZ92XLb6FMqudfN_YRaq-Psh5X2zVD22HNBqMs5gZeCkKk5EeE0RnQRw-s4u8aOUBsLMQFm1h9bItIgh4ZJ9hIJj30-H-p5iw0qZO90TBcjLYmGzK9zvPlB707NkdajWKpc0EdWsSHq_41Z7th2tDb-XNeIULTAfUuha_sKSWE8XNxI-dE3sBlL_45F-jelLwD3lKIc8PgLMbg"

# Environment Pro
#GRAPH_URL_ENTITY = "https://api-core.travelgatex.com/entities/xquery"
#GRAPH_URL_IAM = "https://api-iam.travelgatex.com/controller/xquery"
#GRAPH_TOKEN = "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ik5UZzBPREJGTVRSQ1JURXdOVFEyUkRBek9UbEJRemN4TkVZMU5EUkRPVVJCTVVNMlJqZzVPQSJ9.eyJodHRwczovL3RyYXZlbGdhdGV4LmNvbS9pYW0iOlt7ImEiOm51bGwsImMiOiJ4dGciLCJnIjpbeyJhIjp7ImFsbCI6eyJlbnRpdHkiOnsiYWNjIjpbImNydWQxYWYiXSwiY2xpIjpbImNydWQxYWYiXSwic3VwIjpbImNydWQxYWYiXSwicHJmIjpbImNydWQxYWYiXX0sImhvdGxzdCI6eyJob3QiOlsiMXgiXX0sImh1YmdyYSI6eyJib2siOlsiMXhmIl0sImJvbyI6WyIxeGYiXSwiYnJkIjpbIjF4ZiJdLCJjYXQiOlsiMXhmIl0sImNmZyI6WyIxeGYiXSwiY25sIjpbIjF4ZiJdLCJxdGUiOlsiMXhmIl0sInJvbSI6WyIxeGYiXSwic3JjIjpbIjF4ZiJdfSwiaWFtIjp7ImFwaSI6WyJjcnVkMWFmIl0sImdycCI6WyJjcnVkMWFmIl0sIm1iciI6WyJjcnVkMWFmIl0sInByZCI6WyJjcnVkMWFmIl0sInJvbCI6WyJjcnVkMWFmIl0sInJzYyI6WyJjcnVkMWFmIl0sIm9wdCI6WyJjcnVkMWFmIl19fX0sImMiOiJkZXZvcHMiLCJnIjpudWxsLCJwIjp7ImlhbSI6eyJncnAiOlsiY3J1ZDEiXX19LCJ0IjoidGVhbSJ9XSwicCI6eyJpYW0iOnsiZ3JwIjpbImNydWQxIl19fSwidCI6InJvb3QifV0sImh0dHBzOi8vdHJhdmVsZ2F0ZXguY29tL21lbWJlcl9pZCI6ImRhbWlhbkB4bWx0cmF2ZWxnYXRlLmNvbSIsImlzcyI6Imh0dHBzOi8veHRnLmV1LmF1dGgwLmNvbS8iLCJzdWIiOiJrczJlU0NzQkdMNXQ1dGt6enhGNkVXcWkyeHRlc0lFVUBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9hcGkudHJhdmVsZ2F0ZXguY29tIiwiaWF0IjoxNTM4NjYxMjE2LCJleHAiOjE1NDY0MzcyMTYsImF6cCI6ImtzMmVTQ3NCR0w1dDV0a3p6eEY2RVdxaTJ4dGVzSUVVIiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIn0.K3j-HG1SMJ68OCZ8P-6f1BWtTNroKBlD5TZ6zKLqj7OTb-WgM7bWk2pstv_A1lt2NkEhuE8GHGlj_C4UgNljLoR_WszNZi783e0UNvJrSrP3uSV49GZvTO0pk7prSi2VERc2YAveC3UmI7SojxoQH2RURQjxYQJfYzse97ALPMuwYbtxvJtVlgaVV5xDk6uVWOFrPH9-KHFaT9F39ZsyZqElpbH1Y6-rqbz0Y-k-fP1TsSVFNvUtPsdv73MJtJ8udGsvn1u_K-FC7_-wB0BM72pmcRXvbVK9zaiCuYNqZbF3oqltPsXAgIhwlZUL48dKqpjCQuCPGQi6lF8A1VQkCw"

class GIST_TYPE:
    QA = 0
    DOC = 1
    BOTH = 2

class GIST_CHECK_TYPE:
    JSON = 0
    CALLBACK = 1

class GIST_LEVEL:
    CRITICAL = 2
    MEDIUM = 1
    LOW = 0

class LOG_LEVEL:
    ERROR = "err"
    LOG = "log"
    WARN = "warn"

def getVerbose():
    return VERBOSE

def setVerbose(verbose_value):
    global VERBOSE
    VERBOSE = verbose_value